### ISSUE TITLE
(Wrongly reported - it's about another project) No buttons at all

### ISSUE THREAD

**Issue by avesus** [sproutsocial/github-diff-collapse#1]
There are no your fancy buttons. The plugin doesn't work at all.

**Comment by gordonkristan** [comment]
It seems to be working OK for me (see screenshot). Are you sure the plugin installed properly? Does it show up on the Extensions page and is it enabled?

![screen shot 2015-09-18 at 9 01 21 am](https://cloud.githubusercontent.com/assets/1527297/9961776/0ae31d72-5de8-11e5-8113-f8d9ad5933c5.png)

**Comment by avesus** [comment]
The plugin was installed properly. And it was displayed on the Extensions
page. And my GitHub wasn't in an incognito window.

**Comment by gordonkristan** [comment]
If you open the Chrome console when on a diff page, do you by chance see any errors possibly related to this plugin?

**Comment by avesus** [comment]
Ah, I'll give it a try this week once more. Errors in the console, we could
look at that. Also, please note that my Crome is on Linux CentOS 6.6 and
Chrome is version latest minus one which officially supported there.

Actually, I installed the plugin to _expand_ a diff of a very large file.
GitHub hides the diff from me and my colleagues which leads our new
engineer to seek who was so smart, but we couldn't use Ctrl+F on the PR
page because the diff was hidden.

Does your plugin expanding such absolutely hidden diffs?

**Comment by avesus** [comment]
I am very sorry. There doesn't work _another_ chrome extension, Github-Collapse-Diff.
