### ISSUE TITLE
Multiple buttons

### ISSUE THREAD

**Issue by TheBox193** [sproutsocial/github-diff-collapse#2]
I've noted that when you navigate between pages, using the back button in the browser, additional buttons may be rendered.

Opening an issue to document. May submit a PR if time provides.
![image](https://cloud.githubusercontent.com/assets/220755/10489268/fd451704-7261-11e5-82e5-72f74da463c3.png)

**Comment by gordonkristan** [comment]
I just noticed this yesterday. :smile: If you don't submit a PR I was planning on getting to it this afternoon.

**Comment by TheBox193** [comment]
Whichever, I've been intending to take a look for a while, but haven't had a chance. So feel free, I haven't started debugging. :smile:
