### ISSUE TITLE
formatting screwy when comment count is present on file header and browser width is too narrow / left nav is expanded

### ISSUE THREAD

**Issue by stantonk** [sproutsocial/github-diff-collapse#4]
<img width="506" alt="screenshot 2015-10-20 20 18 12" src="https://cloud.githubusercontent.com/assets/519545/10625331/b4d521fc-7767-11e5-9782-c66f52f4791f.png">

**Comment by stantonk** [comment]
<img width="1439" alt="screenshot 2015-10-20 20 39 22" src="https://cloud.githubusercontent.com/assets/519545/10625625/b0bd357a-776a-11e5-86d7-2f95e06c0035.png">

**Comment by stantonk** [comment]
<img width="1424" alt="screenshot 2015-10-20 20 40 14" src="https://cloud.githubusercontent.com/assets/519545/10625636/e5ecca12-776a-11e5-9c71-21a18fe412aa.png">

**Comment by gordonkristan** [comment]
Closed by 57394e9b69f1bd174ad34b73e94bb79f57a8958a.
