### ISSUE TITLE
Buttons showing on non-diff pages

### ISSUE THREAD

**Issue by vshih** [sproutsocial/github-diff-collapse#7]
Thanks for the extension!

For example:

![Screen Shot 2020-05-20 at 12 50 13 PM](https://user-images.githubusercontent.com/52390/82490700-811ba300-9a98-11ea-8db8-74abbb78d7dc.png)

**Comment by gordonkristan** [comment]
This extension was created at a time when collapsing didn't exist in GitHub. Now you can use [this trick](https://github.blog/changelog/2018-08-17-collapse-all-diffs-in-a-pull-request-at-once/) to collapse all files. [refined-github](https://github.com/sindresorhus/refined-github) also adds several features. I'm going to archive this repo.
